import type { NextPage } from 'next'
import Head from 'next/head'
import { useUnit } from 'effector-react'
import { NavigationContainer } from '../widgets/navigation/navigation.container'
import { navigationService } from '../features/navigation'

import styles from '../shared/styles/home.module.scss'


const Home: NextPage = () => {

  const navigationItems = useUnit(navigationService.outputs.$navigationItems);

  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <NavigationContainer items={navigationItems} />
      </div>
    </div>
  )
}

export default Home
